version: '3.3'

volumes:
  pg_data:
  media_volume:
  static_volume:

services:
  
  db:
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    image: ivanjsx/foodgram_backend:latest
    env_file: ../.env
    volumes:
      - media_volume:/media
      - static_volume:/backend_static
    depends_on:
      - db
  
  frontend:
    image: ivanjsx/foodgram_frontend:latest
    volumes:
      - static_volume:/frontend_static
  
  nginx:
    image: ivanjsx/foodgram_gateway:latest
    ports:
      - 80:80
    volumes:
      - media_volume:/media
      - static_volume:/static
    depends_on:
      - backend      
