version: '3.3'

volumes:
  pg_data_production:
    name: foodgram_pg_data_production
  media_volume:
    name: foodgram_media_volume
  static_volume:
    name: foodgram_static_volume

networks:
  default:
    name: foodgram_default

services:
  
  db:
    container_name: foodgram-db
    image: postgres:13.10
    restart: always
    env_file: ../.env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      timeout: 60s
      interval: 5s
      retries: 12
  
  backend:
    container_name: foodgram-backend
    image: ivanjsx/foodgram_backend:latest
    restart: always
    env_file: ../.env
    volumes:
      - media_volume:/media
      - static_volume:/backend_static
    depends_on:
      db:
        condition: service_healthy
  
  frontend:
    container_name: foodgram-frontend
    image: ivanjsx/foodgram_frontend:latest
    restart: on-failure
    command: cp -r /app/build/. /frontend_static
    volumes:
      - static_volume:/frontend_static
  
  gateway:
    container_name: foodgram-gateway
    image: ivanjsx/foodgram_gateway:latest
    restart: always
    ports:
      - 9000:80
    volumes:
      - media_volume:/media
      - static_volume:/static
    depends_on:
      - backend      
